name: CI

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1️⃣ Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Cache dei node_modules
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Install dipendenze
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run database migrations
      - name: Run database migrations
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
        run: npx dotenv -e .env.test npx drizzle-kit push

      # 5️⃣ Run tests
      - name: Run tests
        env : 
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
          AUTH_SECRET: ${{ secrets.authSecret}}
          AUTH_GOOGLE_ID: ${{ secrets.googleId }}
          AUTH_GOOGLE_SECRET: ${{ secrets.googleSecret }}
        run: npm test
